runtime: go
api_version: go1.9

instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
  max_concurrent_requests: 80

includes:
- handler.yaml
- secret_prod.yaml

skip_files:
- node_modules/
