export default (state = {}, action) => {
	switch (action.type) {
		case 'LOAD_USER_RECOMMEND_DATA_FAILED':
		case 'ADD_RECOMMEND_BRANCH_FAILED':
		case 'UPDATE_RECOMMEND_BRANCH_FAILED':
		case 'DELETE_RECOMMEND_BRANCH_FAILED':
		case 'MOVEUP_RECOMMEND_BRANCH_FAILED':
		case 'MOVEDOWN_RECOMMEND_BRANCH_FAILED':
		case 'MOVE_RECOMMEND_BRANCHES_FAILED':
	}
};


